### PR TITLE
refactor/feat: improve organization of server directory, serve frontscope

### PR DESCRIPTION
**Pull request by liammulh**
This PR improves the organization of the server subdirectory, adds some documentation, adds a script for symlinking server config files to their appropriate locations, and serves frontscope.

### CODE REVIEW

**Comment by gwhitney** [comment]
I read all the changes and they look good. This is hard for me to test locally. Does this _match_ the code currently running on numberscope.colorado.edu? If so, please just go ahead and merge this PR, I have reviewed it by reading code to the extent I can. If there are any differences between this PR and what is running on the numberscope machine, please let me know what they are and I will review.

NOTE that going forward (immediately after this merge) we need to stop making code changes on the server first and then merging them. We need to adopt the workflow of PR, local/GitHub CI testing, merge, _then_ install on the server. We should only ever be installing main on the server. (Except _possibly_ for a rare emergency hotfix.) Thanks!

**Comment by liammulh** [comment]
> Does this match the code currently running on numberscope.colorado.edu?

Yes, this is the code running on the server.

**Comment by liammulh** [comment]
> we need to stop making code changes on the server first and then merging them. We need to adopt the workflow of PR, local/GitHub CI testing, merge, then install on the server.

I would love this.

One of the problems I foresee is adding tests to backscope is going to be hard without doing some refactoring first. (I've been doing a lot of reading about how to test Flask/SQLAlchemy/Postgres.)

What are your thoughts, @gwhitney?

**Comment by liammulh** [comment]
I suppose we could test refactors locally/manually, then add tests.

**Comment by liammulh** [comment]
Also, I don't have a great way to test _server_ config changes (like the changes in this PR) locally.

Maybe I could try to get the server config running on my Linux laptop.

**Comment by liammulh** [comment]
I'm going to merge now since @gwhitney said it was okay to merge.

**Comment by gwhitney** [comment]
Yes, that is correct, going forward at least one reviewer needs to bite the bullet and get the server config running on their local machine for testing purposes, or we need to get a CI server able to run the server config. Let us cross that bridge the next time we need to modify backscope (which will be fairly soon to deal with those sequences that can't load because of crawling too fast).

**Pull request merged**
