### PR TITLE
Add missing period to README.md

### LINKED ISSUE #86: missing period in instructions
https://github.com/numberscope/backscope/blob/210cb8544d976200bd864dc73cc7391f59fe7a72/README.md?plain=1#L36

this should read `source .venv/bin/activate`

### PR DESCRIPTION
**Pull request by gwhitney**
Resolves #86.

### CODE REVIEW

**Comment by gwhitney** [comment]
I think we've made the settings such that there's literally no simple/quick way to fix even a tiny issue like this other than go through this full PR process, so here it is...

**Comment by katestange** [comment]
Ok, I agree the period is in the right place.  Do I need to run the tests to merge this or can I go ahead on pure documention PRs without doing that?

**Comment by gwhitney** [comment]
For a one-character documentation fix I think it is totally fine just to merge. (Once we have automated test runs for every PR the point will become moot, but in the meantime, as far as I am concerned, feel free to just merge (and delete the branch). Best, Glen

**Review by katestange — APPROVED** [review]
The period is in the right place.

**Pull request merged**
