### PR TITLE
feat: Actually use the database to store sequences

### LINKED ISSUE #22: Backend is not using the database to cache sequence values
Looking at the actual code, the backend is not using the database that is being set up for it to store the results of its queries to the OEIS files. Instead it is using a set of plain-text files in a temp directory. UNIX filesystems used in this way are not necessarily "atomic" so if there are two requests in succession for the same sequence, one might produce garbage. The sequence data should be stored/retrieved from the database; such operations are atomic.

### PR DESCRIPTION
**Pull request by gwhitney**
To avoid potential problems with contention for a local files, etc., this PR switches to storing OEIS sequence data in the database, as originally intended.

Resolves #22.

### CODE REVIEW

**Comment by katestange** [comment]
So when I am on the main branch, I do the following to start the server:
```
source .venv/bin/activate
python3 manage.py runserver
```
But when I do that on this pr, I get the following error.  Now, it may be because I need to repeat some portion of the setup in order to incorporate some changes, but I tried to remedy it that way and wasn't very successful.
```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    app = create_app()
  File "/home/katestange/data/projects/numberscope/frontscope-backscope/backscope/flaskr/__init__.py", line 55, in create_app
    from flaskr import nscope
  File "/home/katestange/data/projects/numberscope/frontscope-backscope/backscope/flaskr/nscope/__init__.py", line 5, in <module>
    from .views import bp, executor
  File "/home/katestange/data/projects/numberscope/frontscope-backscope/backscope/flaskr/nscope/views.py", line 11, in <module>
    from flask_executor import Executor
ModuleNotFoundError: No module named 'flask_executor'
```
Anyway, it's probably something dumb I'm doing, but maybe you can advise...

**Comment by gwhitney** [comment]
Hmmm, did you in particular do the `pip install -r requirements.txt` step (once you've activated your virtualenv)? That's definitely necesary -- it's the python equivalent of doing the `npm install` step when you've checked out a new version of the frontscope.

**Comment by katestange** [comment]
Thanks, now it installs and loads.  The pip command produces psychopg errors but the backend loads and responds to the browser.  Only when I test it with
```
http://127.0.0.1:5000/api/get_oeis_sequence/A000045/50
```
then instead of getting the sequence (as on the main branch) the backend reports
```
127.0.0.1 - - [04/Apr/2022 19:40:44] "GET /api/get_oeis_sequence/A000045/50 HTTP/1.1" 404 -
```
and the browser says 404 not found.

**Comment by gwhitney** [comment]
The URL (see frontscope/src/sequences/OEISSequenceTemplate.ts) is `http://127.0.0.1:5000/api/get_oeis_values/A000045/50` [note "values" in place of "sequence"]

**Comment by katestange** [comment]
Would it be appropriate to change the documentation on the backscope (readme.MD) to update this URL there as part of this PR?

**Comment by katestange** [comment]
Now, when I visit that URL I get the attached screenshot.
Screenshot from 2022-04-04 22-37-56

**Comment by gwhitney** [comment]
> Would it be appropriate to change the documentation on the backscope (readme.MD) to update this URL there as part of this PR?

Absolutely. The divergence occurred at some earlier point (this PR didn't change it) but there's no time like the present to fix it. Added a commit that does so.

**Comment by gwhitney** [comment]
> I get the attached screenshot. I'm guessing it's because I didn't reinstall something with this PR

I think it's because you already have an old database that was being used with the backscope. This PR does change the database schema, so you should follow the instructions in the (new version of the) README.md (in this PR) under the heading "Resetting the database". This is good - every aspect of the PR and adapting to it is getting worked out here :)

**Comment by gwhitney** [comment]
(So in particular, feel free to provide feedback on the quality/followability of those instructions.)

**Comment by katestange** [comment]
I'm still having some trouble resetting the database.  I modified the suggested command to 
```
dropdb -U myusernamehere -W numberscope
```
but it's still trying to peer authenticate:
```
dropdb: error: could not connect to database template1: FATAL:  Peer authentication failed for user...
```
Also, the instructions for resetting don't specify if you need to source the environment and/or start postgresql before doing those steps.

**Comment by gwhitney** [comment]
Well, you are definitely on the right track. I have updated the README to include your observations. You should activate the virtual env and make sure the postgresql server is running (I didn't mention that because most ways of installing postgres end up with the server running all the time...)

But then the fact is that your revised command `dropdb -U <user name> -W <database_name>` should work. Look at the contents of your .env file you created in your backscope installation (per what's now step 3 of setup in the README). Are you using the same user name and password as are listed in that .env file? If not, try them. If you are using that user name and password pair than I am stumped at the moment, and we will have to work on this together next time it's convenient for us to connect by video chat with screen sharing possible, e.g., next Monday's meeting. Let me know how it goes.

**Pull request merged**
