### PR TITLE
chore: Update all remaining dependencies.

### LINKED ISSUE #43: Update backscope dependencies
We should be using the newest versions of the dependencies we need for backscope.

### PR DESCRIPTION
**Pull request by gwhitney**
As this involves updating key Flask extensions, testing should involve
  blowing away and recreating the database, as well as other standard
  testing. Of course don't forget to run `sh tools/install-requirements.sh`
  after checking out this branch and before beginning testing.

  Resolves #43.

### CODE REVIEW

**Comment by katestange** [comment]
I had the following error on the first step, installing requirements.
```
Installing backscope dependencies in virtual environment /home/katestange/data/projects/numberscope/frontscope-backscope/backscope/.venv.
Requirement already satisfied: pip in ./.venv/lib/python3.8/site-packages (23.3.1)
Collecting alembic==1.12.0 (from -r requirements-freeze.txt (line 1))
  Downloading alembic-1.12.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: blinker==1.6.3 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 2)) (1.6.3)
Requirement already satisfied: certifi==2023.7.22 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 3)) (2023.7.22)
Collecting charset-normalizer==3.3.1 (from -r requirements-freeze.txt (line 4))
  Downloading charset_normalizer-3.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Requirement already satisfied: click==8.1.7 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 5)) (8.1.7)
Requirement already satisfied: cypari2==2.1.3 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 6)) (2.1.3)
Requirement already satisfied: cysignals==1.11.4 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 7)) (1.11.4)
Requirement already satisfied: Cython==3.0.4 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 8)) (3.0.4)
Requirement already satisfied: Flask==3.0.0 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 9)) (3.0.0)
Collecting Flask-Cors==4.0.0 (from -r requirements-freeze.txt (line 10))
  Downloading Flask_Cors-4.0.0-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask-Executor==1.0.0 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 11)) (1.0.0)
Collecting Flask-Login==0.6.2 (from -r requirements-freeze.txt (line 12))
  Downloading Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Collecting Flask-Migrate==4.0.5 (from -r requirements-freeze.txt (line 13))
  Downloading Flask_Migrate-4.0.5-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: Flask-SQLAlchemy==3.1.1 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 14)) (3.1.1)
Collecting Flask-WTF==1.2.1 (from -r requirements-freeze.txt (line 15))
  Downloading flask_wtf-1.2.1-py3-none-any.whl.metadata (3.4 kB)
Collecting greenlet==3.0.0 (from -r requirements-freeze.txt (line 16))
  Downloading greenlet-3.0.0-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: idna==3.4 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 17)) (3.4)
Requirement already satisfied: itsdangerous==2.1.2 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 18)) (2.1.2)
Requirement already satisfied: Jinja2==3.1.2 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 19)) (3.1.2)
Requirement already satisfied: jsonify==0.5 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 20)) (0.5)
Collecting Mako==1.2.4 (from -r requirements-freeze.txt (line 21))
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 24.5 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe==2.1.3 in ./.venv/lib/python3.8/site-packages (from -r requirements-freeze.txt (line 22)) (2.1.3)
ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement numpy==1.26.1 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4)
ERROR: No matching distribution found for numpy==1.26.1
Failed to install remaining requirements
```

**Comment by gwhitney** [comment]
OK, I pushed a commit backing off to a less recent numpy version that should work with older pythons like yours. You can give it another whirl when convenient.

**Review by katestange — COMMENTED** [review]
I was able to install dependencies, blow away and rebuild database, run and test.  Did you roll back numpy sufficiently for any python >= 3.5, as it says in the docs?  Mine was 3.8.

**Comment by gwhitney** [comment]
Well I updated numpy the most I could without incrementing its minor version number, which will not change its python needs. Will any of the other upgrades need python >3.5 ? I dunno. Best way to check is make a venv with python 3.5 and try. I also don't mind bumping the requirement to 3.8, as 3.5 I'd pretty old. Up to you.

**Comment by katestange** [comment]
Let's just change the docs to require 3.8 then?

**Comment by gwhitney** [comment]
Done. 3.7 and earlier are all already officially end-of-lifed anyway, so the change is pretty much moot.

**Review by katestange — APPROVED** [review]
We pretty much did what was needed in conversation.  I'm happy.

**Comment by Vectornaut** [comment]
Commit `e79a76c` works for me as well!

**Comment by gwhitney** [comment]
(Aside: Note that if you _don't_ quote e79a76c it automagically turns into a link to the commit.)

**Comment by gwhitney** [comment]
Sorry I breached protocol earlier and merged my own PR. I was just a bit overeager to get through this maintenance stuff. Usually whoever approves goes ahead and merges, so I will hold off on this one.

**Pull request merged**
