### PR TITLE
Update format for search by ID

### PR DESCRIPTION
**Pull request by Vectornaut**
This pull request addresses #133 by changing the search query in `get_oeis_name_and_values`. The Requests library automatically URL-encodes the query, so the `:` in the query gets sent as `%3A`.

This pull request is based on #127, which should be merged first. The history associated with this pull request starts at commit 1eec7cd.

### CODE REVIEW

**Comment by gwhitney** [comment]
@Vectornaut, there's no way to review this PR when it is in conflict. And backscope in "main" is in a buggy state with get_oeis_name_and_values because I think that issue will be addressed in this PR. So this PR does need to be reviewed and merged (and fix that issue if it doesn't already) so that we get a working backscope in main that can be installed on the server.

I tried to pull this branch and then `git rebase main` but there are lots of conflicts and frankly I can't tell what's the new stuff from this PR and what is stuff from the last PR that we do need. It's very confusing when there are PRs with 16 commits, some of which seem to either be identical to previous commits or merges of previous commits. I think we will all find life easier if you use git rebase to update your private branches to changes in a shared base branch rather than git merge. In any case, this PR is currently in a state in which I can't see clean code diffs, so I can't review, and also it's in conflict, so it's unmergeable. So when you get a chance, please either resolve the conflicts in this PR, or make a new clean PR based on current main (and hopefully with just one or two commits).

Let me know when that's done and I will review right away. Thanks so much! Glen

**Comment by gwhitney** [comment]
> This pull request is based on #127, which should be merged first. The history associated with this pull request starts at commit [1eec7cd](https://github.com/numberscope/backscope/commit/1eec7cde6c530928c469c3ba54aa801e07735c5d).

If I am reading this correctly, then there is only that one commit that is relevant to this PR, and it is precisely a one-line change. If that's the cae, @Vectornaut, please either change this PR to have just that one commit or create a new PR with just that one-line change and close this one. So hopefully this won't be too much work. The main reason I am not just doing that myself is that if I diff the overall code in this PR with the code in main, there are lots of differences -- but maybe all of the other differences are changes in #127 that occurred after this PR was created, and all that's needed for this PR is that one-line change. It's just hard for me to be sure, whereas I think you might be able to verify this with just a few minutes of looking. Thanks.

**Comment by gwhitney** [comment]
To try to help smooth this along, I made my own private version that consists of main with just the one-line change of commit 1eec7cd. In my (fairly limited so far) testing, it appears to resolve the bug in main from merging #127, of name_and_values not working on "new" sequence ids. However, it's not as simple as merging just that, in that one of the test fails, namely TestUnavailableSearchInNameAndValues. But the failure seems to be that it's still expecting name_and_values to be making the old query. So it seems to me that in addition to the one-line change in views.py, it is either the case that the same change in query has to be made in TestUnavailableSearchInNameAndValues, OR that the test TestUnavailableSearchInNameAndValues needs to be removed altogether, but I am not sure which. Thanks in advance for ironing this out and getting this PR (or a new fresh analogous one) all set to go -- that should get us back in business to work on the frontscope.

**Comment by Vectornaut** [comment]
I just rebased `new-id-search-format` onto the branch that was merged in #127, which should resolve the merge conflicts. The one remaining conflict that GitHub shows is just the one-line change this PR makes.

After rebasing, I confirmed that this PR resolves the [problem](https://github.com/numberscope/backscope/pull/127#issuecomment-2190190317) with  `get_oeis_name_and_values` noticed during review of #127.  Clearing the database and then visiting [`http://localhost:5000/api/get_oeis_name_and_values/A000002`](http://localhost:5000/api/get_oeis_name_and_values/A000002) leads to a sensible-looking response rather than an error.

**Comment by Vectornaut** [comment]
> But the failure seems to be that it's still expecting name_and_values to be making the old query.

Yes, that was it! I've updated the expected response to reflect the new search URL, and the test now passes, so this PR should be ready for review.

**Comment by gwhitney** [comment]
I am not really sure how you are using git, but  GitHub isn't able to follow this git history. It still says the PR is conflicted, which will make it unmergeable. And I can't say I disagree with the notion that there should not be 23 commits for a 2-line change to main ;-)

I will just make a fresh one-commit PR with the two lines of changes, and review that instead.

**Comment by Vectornaut** [comment]
I just merged #140, a single-commit version of this PR, so we don't need this version anymore!

**Pull request closed without merging**
